#!/usr/bin/env python3

import argparse
import json
from pathlib import Path


TRUE_VALUES = {"1", "true", "yes", "on"}
DEFAULT_NO_PROXY = "localhost,127.0.0.1,brale,freqtrade"


def parse_env_file(path: Path) -> dict[str, str]:
    if not path.is_file():
        raise RuntimeError(f"env file not found: {path}")

    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :].strip()
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]
        values[key] = value
    return values


def parse_bool(raw: str | None) -> bool:
    if raw is None:
        return False
    return raw.strip().lower() in TRUE_VALUES


def require_non_empty(env: dict[str, str], key: str) -> str:
    value = env.get(key, "").strip()
    if value == "":
        raise RuntimeError(f"missing required env key: {key}")
    return value


def parse_proxy(env: dict[str, str]) -> tuple[bool, str, str]:
    enabled = parse_bool(env.get("PROXY_ENABLED"))
    no_proxy = env.get("PROXY_NO_PROXY", DEFAULT_NO_PROXY).strip() or DEFAULT_NO_PROXY

    if not enabled:
        return False, "", no_proxy

    raw_port = env.get("PROXY_PORT", "").strip()
    if raw_port == "":
        raise RuntimeError("PROXY_ENABLED=true but PROXY_PORT is empty")
    try:
        port = int(raw_port)
    except ValueError as exc:
        raise RuntimeError(f"PROXY_PORT is not an integer: {raw_port}") from exc
    if port < 1 or port > 65535:
        raise RuntimeError(f"PROXY_PORT out of range [1,65535]: {port}")

    host = (
        env.get("PROXY_HOST", "host.docker.internal").strip() or "host.docker.internal"
    )
    scheme = env.get("PROXY_SCHEME", "http").strip().lower() or "http"
    if scheme not in {"http", "https", "socks5"}:
        raise RuntimeError(f"PROXY_SCHEME unsupported: {scheme}")
    proxy_url = f"{scheme}://{host}:{port}"
    return True, proxy_url, no_proxy


def ensure_map(obj: dict, key: str) -> dict:
    value = obj.get(key)
    if not isinstance(value, dict):
        value = {}
        obj[key] = value
    return value


def mutate_config(
    base: dict, username: str, password: str, proxy_enabled: bool, proxy_url: str
) -> dict:
    api_server = ensure_map(base, "api_server")
    api_server["username"] = username
    api_server["password"] = password

    webhook = ensure_map(base, "webhook")
    webhook["url"] = "http://brale:9991/api/live/freqtrade/webhook"

    exchange = ensure_map(base, "exchange")
    ccxt_config = ensure_map(exchange, "ccxt_config")
    ccxt_async_config = ensure_map(exchange, "ccxt_async_config")

    if proxy_enabled:
        ccxt_config["proxies"] = {"http": proxy_url, "https": proxy_url}
        ccxt_async_config["aiohttp_proxy"] = proxy_url
    else:
        ccxt_config.pop("proxies", None)
        ccxt_async_config.pop("aiohttp_proxy", None)

    return base


def write_proxy_env(
    path: Path, proxy_enabled: bool, proxy_url: str, no_proxy: str
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# generated by scripts/prepare_stack.py"]
    if proxy_enabled:
        lines.extend(
            [
                f"HTTP_PROXY={proxy_url}",
                f"HTTPS_PROXY={proxy_url}",
                f"http_proxy={proxy_url}",
                f"https_proxy={proxy_url}",
            ]
        )
    lines.extend([f"NO_PROXY={no_proxy}", f"no_proxy={no_proxy}"])
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def render_system_config(system_in: Path, system_out: Path, exec_endpoint: str) -> None:
    if not system_in.is_file():
        raise RuntimeError(f"system config not found: {system_in}")

    lines = system_in.read_text(encoding="utf-8").splitlines()
    replaced = False
    rendered: list[str] = []
    for line in lines:
        stripped = line.lstrip()
        if not replaced and stripped.startswith("exec_endpoint") and "=" in stripped:
            indent_len = len(line) - len(stripped)
            indent = line[:indent_len]
            rendered.append(
                f'{indent}exec_endpoint = "{exec_endpoint}" # generated for docker compose'
            )
            replaced = True
            continue
        rendered.append(line)

    if not replaced:
        raise RuntimeError("exec_endpoint key not found in system config")

    system_out.parent.mkdir(parents=True, exist_ok=True)
    system_out.write_text("\n".join(rendered) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Prepare runtime stack config for brale-core + freqtrade"
    )
    parser.add_argument("--env-file", default=".env")
    parser.add_argument("--config-in", default="configs/freqtrade/config.base.json")
    parser.add_argument("--config-out", default="data/freqtrade/user_data/config.json")
    parser.add_argument("--proxy-env-out", default="data/freqtrade/proxy.env")
    parser.add_argument("--system-in", default="configs/system.toml")
    parser.add_argument("--system-out", default="data/brale/system.toml")
    parser.add_argument("--exec-endpoint", default="http://freqtrade:8080/api/v1")
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()

    env_file = Path(args.env_file)
    config_in = Path(args.config_in)
    config_out = Path(args.config_out)
    proxy_env_out = Path(args.proxy_env_out)
    system_in = Path(args.system_in)
    system_out = Path(args.system_out)

    env = parse_env_file(env_file)
    username = require_non_empty(env, "EXEC_USERNAME")
    password = require_non_empty(env, "EXEC_SECRET")
    proxy_enabled, proxy_url, no_proxy = parse_proxy(env)

    if not config_in.is_file():
        raise RuntimeError(f"freqtrade base config not found: {config_in}")
    if not system_in.is_file():
        raise RuntimeError(f"system config not found: {system_in}")

    if args.check_only:
        state = "enabled" if proxy_enabled else "disabled"
        print(f"[OK] precheck passed: proxy={state}")
        return 0

    base = json.loads(config_in.read_text(encoding="utf-8"))
    result = mutate_config(base, username, password, proxy_enabled, proxy_url)

    config_out.parent.mkdir(parents=True, exist_ok=True)
    config_out.write_text(
        json.dumps(result, indent=2, ensure_ascii=True) + "\n", encoding="utf-8"
    )
    write_proxy_env(proxy_env_out, proxy_enabled, proxy_url, no_proxy)
    render_system_config(system_in, system_out, args.exec_endpoint)

    mode = "enabled" if proxy_enabled else "disabled"
    print(f"[OK] generated {config_out} (proxy={mode})")
    print(f"[OK] generated {proxy_env_out}")
    print(f"[OK] generated {system_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
